apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-backend
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-worker
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-frontend
spec:
  replicas: 2
